language : php
php: 
  - '7.0'
  - '7.1'
matrix:
    allow_failures:
        - php: '7.0'
        
before_script:
  - composer install
  
script:
   - phpunit
   - ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock
