language : php
php: 
  - '7.0'
  - '7.1'
matrix:
    allow_failures:
        - php: '7.0'
        
before_script:
  - composer install
  
script:
   - phpunit
   - php app/console security-checker.phar security:check 
