language : php
php: 
  - '7.0'
  - '7.1'
matrix:
    allow_failures:
        - php: '7.0'
 
 
install: 
  - composer global require sensiolabs/security-checker
 
 
before_script:
  - composer install
  
script:
   - phpunit
   - composer global exec --verbose -- security-checker security:check --end-point=http://security.sensiolabs.org/check_lock
