language : php
php: 
  - '7.0'
  - '7.1'
matrix:
    allow_failures:
        - php: '7.0'
        
before_script:
  - composer install
  - php security-checker security:check /path/to/composer.lock
  
script:
   - phpunit
