version: '3'
services:
    mysql:
        image: 'mysql:8'
        ports:
            - '3306:3306'
        volumes:
            - './docker/database:/var/lib/mysql'
        environment:
            - MYSQL_DATABASE=unsecure_db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=hcjkaayd
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
    php:
        image: 'okty/php:7.2'
        volumes:
            - './:/usr/share/nginx/html'
        environment:
            - PHP_EXTENSIONS=pdo_mysql
    nginx:
        image: 'okty/nginx:1.14'
        ports:
            - '8080:80'
        volumes:
            - './:/usr/share/nginx/html'
        environment:
            - MAX_UPLOAD_SIZE=2M
            - PHP_CONTAINER_ID=95338973
            - INDEX_SUBFOLDER=mysql
