unsecure_homepage:
    path:     /Unsecure
    defaults: { _controller: UnsecureBundle:Index:index }
    
unsecure_subject:
    path:     /Unsecure/subject/{subjectId}
    defaults: { _controller: UnsecureBundle:Index:subject }
#    requirements:
#        subjectId: \d+

unsecure_admin:
    path:     /Unsecure/admin
    defaults: { _controller: UnsecureBundle:Admin:index }

unsecure_loginpage:
    path:     /Unsecure/login
    defaults: { _controller: UnsecureBundle:Login:index }

unsecure_logout:
    path:     /Unsecure/logout
    defaults: { _controller: UnsecureBundle:Login:logout }

unsecure_contact:
    path:     /Unsecure/contact
    defaults: { _controller: UnsecureBundle:Contact:index }
    
unsecure_press:
    path:     /Unsecure/press
    defaults: { _controller: UnsecureBundle:Article:index }

unsecure_mynews:
    path:     /Unsecure/my-news
    defaults: { _controller: UnsecureBundle:Index:myNews }
